pipeline {
    agent any

    options {
        timestamps()
        disableConcurrentBuilds()
        skipDefaultCheckout(true)
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code...'

                checkout scm
            }
        }

        stage('Environment') {
            steps {
                dir('user_service') {
                    echo 'Checking build environment...'

                    sh '''
                        echo "Java version:"
                        java -version

                        echo ""
                        echo "Maven version:"
                        chmod +x mvnw
                        ./mvnw -version
                    '''
                }
            }
        }

        stage('Compile') {
            steps {
                dir('user_service') {
                    echo 'Compiling application...'

                    sh './mvnw clean compile'
                }
            }
        }

        stage('Unit Test') {
            steps {
                dir('user_service') {
                    echo 'Running unit tests...'

                    sh './mvnw test'
                }
            }
        }

		stage('SonarQube Analysis') {
		    steps {
		        dir('user_service') {
		            echo 'Running SonarQube analysis...'
		
		            withSonarQubeEnv('sonarqube') {
		                sh '''
		                    ./mvnw org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
		                        -Dsonar.projectKey=ride-hailing-user-service \
		                        -Dsonar.projectName="Ride Hailing User Service"
		                '''
		            }
		        }
		    }
		}

        stage('Package') {
            steps {
                dir('user_service') {
                    echo 'Packaging application...'

                    sh './mvnw package -DskipTests'
                }
            }
        }

        stage('Archive Artifact') {
            steps {
                echo 'Archiving application JAR...'

                archiveArtifacts(
                    artifacts: 'user_service/target/*.jar',
                    fingerprint: true
                )
            }
        }
    }

    post {

        always {
            junit(
                testResults: 'user_service/target/surefire-reports/*.xml',
                allowEmptyResults: true
            )

            cleanWs()
        }

        success {
            echo '''
========================================
BUILD SUCCESSFUL
========================================
Ride Hailing User Service
Branch: development
Application compiled, tested, analyzed and packaged
========================================
'''
        }

        failure {
            echo '''
========================================
BUILD FAILED
========================================
Check the Jenkins console output.
========================================
'''
        }
    }
}